shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = """{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source "{{ file }}"\n{% endfor %}{{ hooks?.post | nl }}"""

# 入力候補をグレー表示（便利さ体感度が高い）
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

# コマンドの色付き表示
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

# 追加の補完定義
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]
