#!/usr/bin/env zsh

#
# Path settings
#

# cuda/binはdocker内でGPUが使えない問題の解決に必要
typeset -gU path fpath
path=(
    $path
    /usr/local/{,s}bin(N-/)
    /usr/local/cuda/bin(N-/)
    ${HOME}/.local/bin(N-/)
    ${HOME}/.local/bin/common(N-/)
)
fpath=(
    $fpath
    ${HOME}/.local/bin/common(N-/)
)

# export PATH=/usr/local/cuda/bin:$PATH
# export PATH="$HOME/.local/bin:$PATH"
eval "$(starship init zsh)"
eval "$(sheldon source)"
eval "$(/home/zenimoto/.local/bin/mise activate zsh)"
alias cz="chezmoi"
# デフォルトオプション
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'

# Ctrl+T でプレビュー付きにする
export FZF_CTRL_T_OPTS="--preview 'bat -n --color=always {}' --bind 'ctrl-/:change-preview-window(hidden|)'"

# fd を使って高速化 (.gitignore を尊重)
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git'
# test
cd() {

  builtin cd "$@" && ls

}
